#+title: Exposing C++ Libraries with clbind
#+OPTIONS: ^:nil

* Note on this document
This document contains information on creating was created by piecing together information from different sources during the creation of the SFML binding.
It is the result of conversations on #clasp, trial and error, and reading source code, provided in the hope that it can help other early adopters of clasp.
It is not an official documentation, and is neither complete nor does it claim correctness.

Due to the alpha status of clasp, everything in this document is subject to change.

* General information
clbind is based on luabind. Many things can be derived from looking at the [[http://www.rasterbar.com/products/luabind/docs.html][luabind documentation]].

* Structure of a Binding
Clasp is able to load c++ libraries. Because C++ has no standard for its name mangling, Clasp needs an entrance point that it can find in every exposed library and from where it can derive the names of all other exposed functionality. This entrance point is provided by an ~extern "C"~ function called ~CLASP_MAIN~. 
Within this function, packages can be declared that will contain methods exposing the desired functionality within Clasp.

Thus, code should include a section like this:


#+BEGIN_SRC C++
extern "C" 
{
  EXPORT
  void CLASP_MAIN()
  {
    using namespace clbind;
     package("package-name")
     [
       //exposure of classes and functions for use in this package
     ];
  }
}
#+END_SRC

* Include Files
Compiling the binding requires the inclusion of several header files. Some of those are required, while some are only needed if [[Translators][translators]] are being written or existing translators, e.g. for string conversion are being used. These are the files I currently include, the status is not clear on all of them:
#+BEGIN_SRC C++
#include "src/clbind/clbind.h"       //required (or really just clbind/clbind.h ?)
#include "src/core/lispVector.h"     //required, if writing converters
#include "src/core/vectorObjects.h"  //for automatic conversion from and
#include "src/core/cons.h"           //into c++ objects.
#include "src/core/translators.h"    //assorted translators for string etc
#+END_SRC

* Exposing Functions
Exposing functions is done via the function ~def~:
#+BEGIN_SRC C++
template <typename F, class Policies>
scope def(char     const* name,
          F               f,
          Policies const& policies,
          string   const& lambdalist = "",
          string   const& declares   = "",
          string   const& docstring  = "" )
#+END_SRC
In this function
- name :: is the name that the function will have in clasp. It is automatically lispified, i.e. a name  with camel-casing is converted to a downcase name with dashes in between. Using this automatic lispification is optional, and it can be useful to use names following lisp conventions, so that a reader can immediately see how the respective lisp function is called.
- f :: is the function pointer to the c++ function.
- policies :: Gives additional information about how to handle some parameters (see [[Policies][Policies]]). An overloaded version of def does not have this parameter and uses the standard ~policies<>()~.
- lambdalist :: This optional parameter is an ordinary [[http://www.lispworks.com/documentation/lw60/CLHS/Body/03_da.htm][lambda-list]] as in Common Lisp's ~defun~. For every binding in the lambda list there has to be a corresponding argument in the C++ function. If the argument is an empty string, every parameter of the C++ function will be a required parameter in Common Lisp, even those that have default initializers. It is highly recommended to not leave the lambda list empty, even if you want to expose all parameters in a standard fashion. The lambda list provided here is used by slime for all kinds of support, e.g. to name and highlight the parameters when writing a function.
The lambda list is evaluated by lisp. As a consequence having ~&optional~ parameters without an init-form is normally not a good idea, as ~nil~ would be passed to the function. Unless you have written a [[Translators][translator]] that translates from ~nil~ to the required type, this will not work. Specifically, it might be tempting to think that providing an optional parameter in a lambda list for a parameter that has a default value in the C++ function would select that default value. However, this is not the case. You need to provide the lisp equivalent of that default value as an init-form to the optional parameter.
- declares :: This optional parameter represents the declaration part of a Common Lisp defun, but is currently unused.
- docstring :: This optional parameter defines the docstring that is used for this function within clasp, e.g. for functions like ~documentation~ and ~describe~. This is currently non-working, due to a bug.

Suppose a C++ function 
#+BEGIN_SRC C++
double addThreeNumbers(double x, double y, double z);
#+END_SRC
A complete binding could look like this (only the first two parameters are required) 
#+BEGIN_SRC C++
def("addThreeNumbers", &addThreeNumbers, policies<>(),
    "(x &optional (y 0) (z 0))", "",
    "Return the addition of all three arguments. y and z are optional and default to 0."),
#+END_SRC
From clasp, this function can be called with 
~(add-three-numbers 1)~ or ~(add-three-numbers 1 2)~ or ~(add-three-numbers 1 2 3)~.
The C++ function is called as ~addThreeNumbers(1,0,0)~, ~addThreeNumbers(1,2,0)~ and ~addThreeNumbers(1,2,3)~, respectively.

** Overloaded Functions
To expose overloaded functions, you have to cast the function pointer to the correct signature. Suppose the function from the previous example would be overloaded. It would then need an exposure such as this:
#+BEGIN_SRC C++
def("addThreeNumbers", (double(*)(double, double, double)) &addThreeNumbers),
#+END_SRC

* Exposing Classes
Exposing a class is done via the class ~class_~:
#+BEGIN_SRC C++
class_<CppClassName>("lisp-class-name")
#+END_SRC
Creates a Binding to the C++ class ~CppClassName~, with the name ~lisp-class-name~ in lisp.
This automatically creates a binding to the default constructor as well. (?? The default constructor is called ~default_ctor~ - how are default constructors differentiated ??)
To prevent the automatic creation of a default constructor, use a second parameter:
#+BEGIN_SRC C++
class_<CppClassName>("lisp-class-name", no_default_constructor)
#+END_SRC

** Inheritance
clbind can handle member functions of derived classes correctly, providing that they are exposed.
To expose the inheritance structure of C++ classes, expose the base class, and use the following format for the derived class:
#+BEGIN_SRC C++
class_<CppDerivedClassName, CppBaseClassName>("lisp-class-name")
#+END_SRC
If multiple inheritance brings in several base classes, use the following format:
#+BEGIN_SRC C++
class_<CppDerivedClassName, bases<CppBaseClassName1, CppBaseClassName2>>("lisp-class-name")
#+END_SRC
If a base class is a pure virtual class, i.e. it has only pure virtual functions or its constructor is private, make sure to use the ~no_default_constructor~ option when exposing the base class, otherwise you will get a compilation error.

** Constructors
Add constructors to exposed classes with the function ~def_constructor~:
#+BEGIN_SRC C++
template<typename... Types>
class_& def_constructor(const string&         name,
                        constructor<Types...> sig,
                        const Policies&       policies,
                        string const&         arguments = "",
                        string const&         declares  = "",
                        string const&         docstring = "")
#+END_SRC
In this function
- name :: is the name of the constructor that will be visible in clasp. Again, it will be lispified.
- sig :: is the parameter signature of the C++ constructor. Use a comma-separated parameter-list list in the form ~constructor<parameter-list>()~ of all the types used as parameters in the constructor you want to expose.
- policies, arguments, declares, docstring :: Optional parameters, explained in [[Exposing Functions][Exposing Functions]]

** Member Functions
Exposing member functions is similar to exposing free functions. Call the ~class_~ member function ~def~:
#+BEGIN_SRC C++
template<class F, class DefaultOrPolicies>
class_& def(char const*       name, 
            F                 fn, 
            DefaultOrPolicies default_or_policies,
            string const&     arguments = "",
            string const&     declares  = "",
            string const&     docstring = "")
#+END_SRC
Thus exposing a member function is not different from [[Exposing Function][exposing free functions]], and the same arguments apply. (?? difference between policies and DefaultOrPolicies ??)
The exception to this rule is the lambda-list (arguments), which always requires ~self~ as its first parameter, which becomes the ~this~ argument within the method.

** Static Member Function
As Common Lisp does not have the notion of static member functions, exposing them is similar to [[Exposing Functions][exposing free functions]].

** Public Member Variables
Exposing public member variables works similar to exposing member functions. 

* Translators
Translators can be used to automatically convert C++ objects to Common Lisp objects and vice versa. This is mainly a convenience functionality, allowing for easier integration. It is especially useful for small C++ classes and structs that are passed to and from functions and are meant to be created on the fly. Instead of exposing them and then creating and filling them from Common Lisp, it is often easier to write a translator, e.g. from a list, which makes it possible to pass a list as a parameter in place of the object. This list is then automatically converted to the respective C++ object by the translator.

(?? Translators are missing info on pointer adoption, true_type, false_type,... ??)

** Translation from C++ objects to Common Lisp objects 
Translating from C++ to Common Lisp objects is done by specializing the templated struct ~to_object~ in the namespace ~translate~ to the type of the C++ object, with the static function member function convert of that struct taking an object of that type as a parameter and returning the Clasp Common Lisp Object:
#+BEGIN_SRC C++
namespace translate
{
  template <>
  class to_object<CppTypeToTranslateFrom> 
  {
    static core::T_sp convert(CppTypeToTranslateFrom cppObject)
    {
       core::Cons_sp cons; //use a cons object in this example
       //convert cppObject to an object derived from core::T_sp (here: Cons_sp).
       return cons;
    }
  };
};
#+END_SRC


** Translation from Common Lisp objects to C++ objects 
Translating from Common Lisp to C++ objects is done by specializing the templated struct ~from_object~ in the namespace ~translate~ to the C++ object type and providing a constructor that takes the Common Lisp object as a parameter and writes the result into an object called _v of the C++ object type:
(?? is the typedef DeclareType a must or just a convention ??)
#+BEGIN_SRC C++
namespace translate
{
  template <>
  struct from_object<CppTypeToTranslateTo> 
  {
    typedef CppTypeToTranslateTo DeclareType;
    DeclareType _v;
    from_object(const core::T_sp& obj)
    {
      //convert obj and store the result in _v.
    }
  };
};
#+END_SRC

* Exposing Enums
Exposing Enums is not finalized, yet. 
See [[https://github.com/HeyFlash/SFML/blob/master/include/CLASP-SFML/Window/Event.hpp][ClaspBindingWindow]] and [[https://github.com/HeyFlash/SFML/blob/master/include/CLASP-SFML/Window/Event.hpp][Event translators]] in the SFML binding for currently working translators. This *will break* in future releases of Clasp.

* Policies
??
