#+title: Implementation details
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="styles/readtheorg/css/htmlize.css"/><link rel="stylesheet" type="text/css" href="styles/readtheorg/css/readtheorg.css"/><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script><script type="text/javascript" src="styles/lib/js/jquery.stickytableheaders.min.js"></script><script type="text/javascript" src="styles/readtheorg/js/readtheorg.js"></script>

* Clasp Startup

Clasp has a variety of ways that it can startup.

1. Clasp can startup from a "snapshot" - this is the fastest startup. 
  + Snapshots are recordings of memory that were created using a running Clasp. =(gctools:save-lisp-and-die)= creates a snapshot within a running Clasp that is written into "app-fasl:<executable-name>.snapshot".

2. Clasp can startup from a snapshot embedded within the executable.

3. Clasp can startup from an "image" - this is a fasl file that contains compiled Common Lisp code. 
  + Clasp replays all of the top level forms when it loads an image. This startup can take anywhere from a few seconds to tens of seconds for cando or other extensions that use lots of quicklisp systems.


** Command Line Options That Control Startup

- -T/--type (default|snapshot|image)
- -i/--image <filename>  
- -I/--ignore-image 
- -n/--noinit 

=-T default= (the default) means first attempt to load the default snapshot file and if its not found then proceed 
   to the default image file and if that is not found then terminate with an error.

=-T snapshot= means load the default snapshot file and if not found then terminate with an error. The default
snapshot file is (in the Common Lisp logical pathname notation) "app-fasl:<executable-name>.snapshot".

=-T image= means load the default image file and if that is not found then terminate with an error. The default image file is (in the Common Lisp logical pathname notation) "app-fasl:<executable-name>.<fasl-extension>". The <fasl-extension> changes depending on how clasp is built.

=-i <filename>= means if the filename ends in ".snapshot" then load it as a snapshot file. If <filename> does not end in ".snapshot" then load it as an image - otherwise signal an error. The -T and -i options are mutually exclusive. The -i option will override the -T option.

=-I= means don't load snapshot or image files. Instead proceed to load the kernel/init.lsp file.

=-n= Used with -I. If this is passed then don't load the init.lsp file. This will start a very bare bones REPL and load no Common Lisp code.

Examples:
  + =clasp= :: Will try to load "app-fasl:clasp.snapshot" and then "app-fasl:clasp.<fasl>" and if it doesn't find that - it will terminate with an error.
  + =clasp -T image= :: Will try to load "app-fasl:clasp.<fasl>" and if it isn't found - clasp will terminate with an error.
  + =clasp -I -n= :: Will start a primitive clasp REPL without loading any snapshot, image, or Common Lisp source code. It will start the pidgin Common Lisp interpreter.
  + =clasp -I= :: Will load the "sys:kernel;init.lsp" source file and start the pidgin Common Lisp interpreter.

* Executables with embedded snapshots

Executables with embedded snapshots always use those snapshots.

* Fasp files
See [[file:fasp.org][Fasp files are concatenated object files.]]
* Profiling clasp and C++

You can profile Clasp compiled code and C++ together. On linux we use the ~perf~ tools to generate profile data and on macOS we use ~dtrace~.

** Profiling on linux

Clasp generates just in time (JIT) code for which we need symbol information. Use the ~(ext:generate-perf-map)~ function within clasp to generate a ~/tmp/perf-<pid>.map~ file that ~perf~ will use to convert addresses to symbols.  Do this just prior to evaluating the code that you want to profile so that you get the maximum coverage of JITted symbols.

#+BEGIN_SRC lisp
COMMON-LISP-USER> (ext:getpid)

33159
COMMON-LISP-USER> (defun fibonacci (n)
  (declare (fixnum n) (optimize (debug 0) (speed 3) (safety 0)))
  (cond
   (;; Base case.
    ;; The first two Fibonacci numbers (indices 1 and 2) are 1 by definition.
    (<= n 2)  ;; If n <= 2
    1         ;; then return 1.
    )
   (t                               ;; else
    (+                              ;; return the sum of
     ;; the results of calling
     (fibonacci (- n 1))            ;; fibonacci(n-1) and
     (fibonacci (- n 2))            ;; fibonacci(n-2).
     ;; This is the recursive case.
     ))))

FIBONACCI
COMMON-LISP-USER> (ext:generate-perf-map)
Writing to /tmp/perf-33159.map
COMMON-LISP-USER> (time (dotimes (i 10) (fibonacci 41)))
#+END_SRC

In another window, within the FlameGraph directory do the following..

#+BEGIN_SRC sh
$ sudo sysctl -w kernel.perf_event_max_stack=1024              # (1)
$ perf record -F 99 -p 33159 -g -o /tmp/perf.data -- sleep 10  # (2) 
[ perf record: Woken up 4 times to write data ]
[ perf record: Captured and wrote 0.873 MB perf.data (983 samples) ]
$ perf script -i /tmp/perf.data --max-stack 1024 | ./stackcollapse-perf.pl >/tmp/out.perf-folded # (3)
$ ./flamegraph.pl /tmp/out.perf-folded >/tmp/perf.svg # (4)
#+END_SRC

1. The profiling stack is only 127 frames deep by default. This will increase it to 2048.
2. Record the perf data for our process. This needs to run during the time consuming process in Clasp.
3. Generate the backtraces and fold them according to the flame graph instructions.
4. Generate the flame graph.

Then open the ~/tmp/perf.svg~ file in a web browser or svg file viewer.
