#+title: Clasp --- Bringing Common Lisp and C++ Together

Clasp is a new [[https://common-lisp.net/][Common Lisp]] implementation
that seamlessly interoperates with C++ libraries and programs using
[[http://llvm.org/][LLVM]] for compilation to native code. This allows
Clasp to take advantage of a vast array of preexisting libraries and
programs, such as out of the scientific computing ecosystem. Embedding
them in a Common Lisp environment allows you to make use of rapid
prototyping, incremental development, and other capabilities that make
it a powerful language.

* Getting Clasp

Precompiled and prepackaged versions of Clasp will be available for a
limited number of distributions. Check the
[[https://github.com/drmeister/clasp/releases][releases]] to see if there is something available for you.

* Common Lisp Ecosystem Support

Clasp supports [[https://common-lisp.net/project/slime/][SLIME]],
[[https://common-lisp.net/project/asdf/][ASDF]], and
[[https://www.quicklisp.org/beta/][Quicklisp]]. As such, development as
in other Common Lisp implementations should be rather straight forward.

Note that Clasp does not currently support several of the staple
features such as
[[https://github.com/drmeister/clasp/issues/162][CFFI]],
[[https://github.com/drmeister/clasp/issues/163][Bordeaux-Threads]], and
[[https://github.com/drmeister/clasp/issues/164][Unicode]].

* Reporting Problems

Generally you can report problems in two fashions, either by
[[https://github.com/drmeister/clasp/issues/new][opening an issue
ticket]] or by [[#irc][chatting with us directly]]. In both cases,
though, you should have the following pieces handy in order for us to be
able to help you out as quickly and painlessly as possible.

-  Your operating system name and version.
-  The versions of the [[#external-dependencies][external libraries]]
   that you have installed.
-  A paste of the build log or failure point that you reached.
-  Patience.

* Acknowledgments
Clasp was supported by the Defense Threat Reduction Agency (DOD-DTRA)
(HDTRA1-09-1-0009) the National Institutes of Health (NIH/NIGMS Grant
number: 2R01GM067866-07A2) and the National Science Foundation (Grant
number: 1300231).
